In [11]:
#Importing Important Libraries

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import keras

In [2]:
# Making accessible to google drive

from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
# Reading the dataset

df = pd.read_csv('/content/drive/My Drive/IRIS.csv')
df.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [4]:
# Checking basic info of dataset

print(df.shape)
df.describe()

(150, 5)


sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [5]:
# Using sklearn library to label species

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['species'] = le.fit_transform(df['species'])
df.head()

sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [6]:
# Number of classes: 0 = Iris-setosa, 1 = Iris-versicolor, 2 = Iris-virginica

species_name = le.classes_
print(species_name)

['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']


In [7]:
# Splitting the dataset into feature and predictors

predictors = df.drop(columns=["species"])
target = df["species"]

print(target.head(3))
predictors.head(3)

0    0
1    0
2    0
Name: species, dtype: int64


sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2

In [8]:

# Splitting Data into train (70%) and test (30%) dataset

X_train, X_test, y_train, y_test = train_test_split(predictors, target, test_size=0.3, shuffle = True, random_state=70)
print(X_train.shape)
print(X_test.shape)

(105, 4)
(45, 4)


In [9]:
# Scaling of Dataset using sklearn

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)           # It alreay Fit

In [12]:
# Converting y_train into 2D Binary Matrix

y_train = keras.utils.to_categorical(y_train, num_classes = 3)
print(y_train[:5])

[[1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


In [13]:
# Importing Sequential and Dense library from keras

from keras.models import Sequential
from keras.layers import Dense, Dropout


In [14]:
# Creating Model

model = Sequential()
model.add(Dense(units = 40, activation = 'relu', input_shape = (4,)))
model.add(Dense(units = 40, activation = 'relu'))
model.add(Dropout(0.45))      # ---------------------------------------------------->> Helps to avoid overfitting
model.add(Dense(units = 3, activation = 'softmax'))

In [15]:
# Compiling Model

model.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 40)                200       
                                                                 
 dense_1 (Dense)             (None, 40)                1640      
                                                                 
 dropout (Dropout)           (None, 40)                0         
                                                                 
 dense_2 (Dense)             (None, 3)                 123       
                                                                 
Total params: 1,963
Trainable params: 1,963
Non-trainable params: 0
_________________________________________________________________


In [17]:
# Model Fitting

model.fit(X_train, y_train, epochs = 100, verbose = 1)


Epoch 1/100
4/4 [==============================] - 1s 8ms/step - loss: 1.1351 - accuracy: 0.2857
Epoch 2/100
4/4 [==============================] - 0s 6ms/step - loss: 1.0979 - accuracy: 0.3333
Epoch 3/100
4/4 [==============================] - 0s 5ms/step - loss: 1.0384 - accuracy: 0.4952
Epoch 4/100
4/4 [==============================] - 0s 5ms/step - loss: 1.0198 - accuracy: 0.5429
Epoch 5/100
4/4 [==============================] - 0s 5ms/step - loss: 0.9517 - accuracy: 0.6286
Epoch 6/100
4/4 [==============================] - 0s 4ms/step - loss: 0.9182 - accuracy: 0.6286
Epoch 7/100
4/4 [==============================] - 0s 4ms/step - loss: 0.8972 - accuracy: 0.6952
Epoch 8/100
4/4 [==============================] - 0s 4ms/step - loss: 0.8500 - accuracy: 0.8000
Epoch 9/100
4/4 [==============================] - 0s 5ms/step - loss: 0.7958 - accuracy: 0.8381
Epoch 10/100
4/4 [==============================] - 0s 5ms/step - loss: 0.7879 - accuracy: 0.7905
Epoch 11/100
4/4 [===========

In [24]:
# Making Predictions

predictions = model.predict(X_test)
print(predictions[:5])

2/2 [==============================] - 0s 8ms/step
[[9.9957103e-01 4.2402995e-04 4.8936304e-06]
 [9.8980388e-05 1.9736586e-02 9.8016447e-01]
 [2.0750506e-02 9.0834939e-01 7.0900112e-02]
 [6.1237565e-03 9.8094964e-01 1.2926548e-02]
 [8.5859167e-05 3.1378034e-03 9.9677640e-01]]


In [25]:
# Converting result to more visible form

prediction = np.argmax(predictions, axis = -1)
print(prediction[:5])

[0 2 1 1 2]


In [26]:
# Cross Checking

print(y_test[:5])

18     0
107    2
91     1
69     1
104    2
Name: species, dtype: int64


In [28]:
# Checking the Acurracy of Model

from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, prediction))

1.0
